### ISSUE TITLE
Error verifying manifest: Exception reading manifest when using the install option

### ISSUE THREAD

**Issue by decrypter82** [PaaaulZ/SilentClickOnce#11]
Hi Paul.

Its me again. the uninstall parameter worked great in the other post. I am now using the -i parameter and I get this error: 
[2023-07-03 10:58:02] [?] Starting setup.
[2023-07-03 10:58:02] [-] Error verifying manifest: Exception reading manifest from file://10.140.68.15/05%20IT/CTDI%20Software/TWC/CTDI%20TWC.appref-ms: the manifest may not be valid or the file could not be opened.

Originally the Clickonce App comes in an compiled Exe file which I already tried and I get same error. Without your tool the app installs fine whatever double clicking the exe or the with the .appref-ms file extension. Both asks the user to install or not to install.

If I use your tool I get the error above. Any ideas? File exists in location. I also tried copying the installer locally in the device and same issue.
Sorry to mess your day.

**Comment by PaaaulZ** [comment]
Try using the UNC notation like : "\\10.140.68.15\05 IT\CTDI Software\TWC\CTDI TWC.appref-ms", also you can try replacing %20 with spaces and putting everything in quotes like: "file://10.140.68.15/05 IT/CTDI Software/TWC/CTDI TWC.appref-ms"

I'm sure with the first one it will work

Consider that if 10.140.68.15 requires authentication you can have problems based on how you run the command

**Comment by decrypter82** [comment]
Ok. the ip requires authentication so, I decided to use a local install. but I gave another try as I have the credentials stored.

SilentClickOnce -i "file://10.140.68.15/Orlando_Local_Share/05 IT/CTDI Software/TWC/CTDI TWC.appref-ms" > insta1.log

I get this:
[2023-07-03 13:22:05] [?] Starting setup.
[2023-07-03 13:22:05] [-] Error verifying manifest: Exception reading manifest from file://10.140.68.15/Orlando_Local_Share/05%20IT/CTDI%20Software/TWC/CTDI%20TWC.appref-ms: the manifest may not be valid or the file could not be opened.

The following are by having the install file locally.

I tried SilentClickOnce -i "C:\Apps\CTDI TWC.appref-ms" > insta1.log
 I get this:
[2023-07-03 13:18:36] [?] Starting setup.
[2023-07-03 13:18:37] [-] Error verifying manifest: Exception reading manifest from file:///C:/Apps/CTDI%20TWC.appref-ms: the manifest may not be valid or the file could not be opened.

I tried SilentClickOnce -i "C:\Apps\TWC App Launcher.exe" > insta1.log
[2023-07-03 13:26:16] [?] Starting setup.
[2023-07-03 13:26:16] [-] Error verifying manifest: Exception reading manifest from file:///C:/Apps/TWC%20App%20Launcher.exe: the manifest may not be valid or the file could not be opened.

Here is the local route

![image](https://github.com/PaaaulZ/SilentClickOnce/assets/26398249/e6320957-4235-4c83-be62-682c49af020f)

**Comment by PaaaulZ** [comment]
Are you sure that "CTDI TWC" is a .appref-ms and not .application? Try with **SilentClickOnce -i "C:\Apps\CTDI TWC.application" > insta1.log**
It's weird because it looks like a file not found error

**Comment by decrypter82** [comment]
Yeah. Its weird. 
Tried SilentClickOnce -i "C:\Apps\CTDI TWC.application" > insta1.log
and I get:
[2023-07-03 14:38:33] [?] Starting setup.
[2023-07-03 14:38:33] [-] Error verifying manifest: Downloading file:///C:/Apps/CTDI TWC.application did not succeed.

This is how its shown in the DOS Console.

![image](https://github.com/PaaaulZ/SilentClickOnce/assets/26398249/31c33292-5c6b-43ed-85d4-efaf97891ba3)

**Comment by PaaaulZ** [comment]
Can you try running the prompt with admin priviledges? maybe C:\ has restricted access

**Comment by decrypter82** [comment]
Same thing. I have an admin account but I ran it as administrator and I got same issue. I cant sees why manually without the tools works fine the install by clicking it manually either the exe or the appref-sm but this tool not. File locations are fine but if the manifest is not valid why it runs fine manually? No idea :-(

**Comment by PaaaulZ** [comment]
I really have no clue, you can check with notepad if inside the .appref-ms you have the same path, for now I don't have ideas :c

**Comment by decrypter82** [comment]
Here is what .appref-ms has

http://appdeploy.ctdi.com/STB.TWC.OLP.AppLauncher.WinApp/STB.TWC.OLP.AppLauncher.WinApp.application#STB.TWC.OLP.AppLauncher.WinApp.application, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86

**Comment by PaaaulZ** [comment]
Ok now I understand.
The .appref-ms is the file you use to launch the application when is installed, to install with this software you need a path to the .application file so the command should be: `SilentClickOnce.exe -i "http://appdeploy.ctdi.com/STB.TWC.OLP.AppLauncher.WinApp/STB.TWC.OLP.AppLauncher.WinApp.application"`. The problem is that the URL you provided where the software files should be returns 404

It's like that URL is not valid anymore so it has nowhere to download the program files, looks like there is no bug to look for

**Comment by decrypter82** [comment]
You are the best, bro. it worked. Thanks once again. :-)
