### ISSUE TITLE
Uninstall Parameter

### ISSUE THREAD

**Issue by Timhe23** [PaaaulZ/SilentClickOnce#3]
Hi,

installation is working fine, thanks.

But how to uninstall the app? It doesnt work like mentioned.
"SilentClickOnce.exe -u Appname> myappuninst.log"
For uninstall, I dont use the .application file or am i wrong? I've used the Name how it is shown in Apps & Features.
I always get the error "[-] Error uninstalling exception has been thrown by the target of an invocation."

Thanks for help.

**Comment by PaaaulZ** [comment]
You should use the name of the .application or the .appref-ms file, if the file is named Program.application you should put **Program**
Be sure to put a space after the appname, like: "SilentClickOnce.exe -u Program > myappuninst.log"

Let me know if it helps

**Comment by PaaaulZ** [comment]
Hi, can you try with new version v1.3b? Thanks

EDIT: Closed (see #4 )
