### ISSUE TITLE
Can't uninstall app

### ISSUE THREAD

**Issue by BimalParmar** [PaaaulZ/SilentClickOnce#4]
Hi, I have successfully used SilentClickOnce to install silently.

However I would like to silently uninstall, but it gives the below error.
So i am running the following command for Tradesignal click once app:
SilentClickOnce.exe -u Tradesignal > Uninstall.log

The log states Error uninstalling Object reference not set to an instance of an object.

When I look at the registry entry for this click once app, its referenced Tradesignal.app and not .application.

Looking at the new uninstall fix code, i can see it referencing {applicationName}.application

Can you help?

Thanks.

**Comment by PaaaulZ** [comment]
Hi, can you try with the new version v1.3b and let me know if it works? Thanks

**Comment by BimalParmar** [comment]
Excellent

Just tried that and it works a treat, uninstalls successfully.

Thank you very much
😄
