### ISSUE TITLE
Error exception thrown when uninstalling

### ISSUE THREAD

**Issue by daniarv** [PaaaulZ/SilentClickOnce#7]
Hi,

When I try to uninstall a application with the following command:

`SilentClickOnce.exe -u AppName`

...I will get this error and then nothing more happens:

`Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
[2023-06-01 14:48:01] [-] Error uninstalling: Exception has been thrown by the target of an invocation.
The program '[5844] SilentClickOnce.exe' has exited with code 1 (0x1).`

Do you know what is causing this?

**Comment by daniarv** [comment]
Hi again,

After debugging the code in Visual Studio I found the problem and it seems that the saved uninstallString variable is wrong.
I had to add this to get it working:


```
            Dim correctUninstallString As String

            Dim startIndex As Integer = uninstallString.IndexOf("ShArpMaintain ")
            If startIndex <> -1 Then
                correctUninstallString = uninstallString.Substring(startIndex + "ShArpMaintain ".Length).Trim()
            Else
                correctUninstallString = uninstallString ' Word not found, keep the original line
            End If
```


And then change this:
`Dim subState As Object = _r_m_GetSubscriptionState.Invoke(deploymentServiceCom, New Object() {correctUninstallString})`

**Comment by PaaaulZ** [comment]
Can you send me the uninstallString? You can censor the app name if you want
I've never seen a clickonce unistalled without calling ShArpMaintain and I'm curious to debug it

**Comment by daniarv** [comment]
Hi,

This is my uninstall string found from the registry:

`rundll32.exe dfshim.dll,ShArpMaintain UtbildningsDb.application, Culture=sv, PublicKeyToken=9ecf5093ba3f717e, processorArchitecture=x86`

But string that I have to use to got it working is this:

`UtbildningsDb.application, Culture=sv, PublicKeyToken=9ecf5093ba3f717e, processorArchitecture=x86`

Followed by your original code:

`            Dim deploymentServiceCom As New System.Deployment.Application.DeploymentServiceCom()
            Dim _r_m_GetSubscriptionState As Reflection.MethodInfo = GetType(System.Deployment.Application.DeploymentServiceCom).GetMethod("GetSubscriptionState", System.Reflection.BindingFlags.NonPublic Or System.Reflection.BindingFlags.Instance)
            Dim subState As Object = _r_m_GetSubscriptionState.Invoke(deploymentServiceCom, New Object() {correctUninstallString})
            Dim subscriptionStore As Object = subState.GetType().GetProperty("SubscriptionStore").GetValue(subState)
            subscriptionStore.GetType().GetMethod("UninstallSubscription").Invoke(subscriptionStore, New Object() {subState})`

**Comment by PaaaulZ** [comment]
I updated the code and added a new release, please check with the new version.
Publish your log and uninstallString again if you have any problem

Thank you
