### ISSUE TITLE
Error uninstalling Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by dev-charlz** [PaaaulZ/SilentClickOnce#8]
This app works great for installing, but I'm getting the following error when trying to use it to uninstall:
[2023-06-05 18:33:43] [-] Error uninstalling Object reference not set to an instance of an object.

For reference, here is what the uninstall string looks like for this app:
rundll32.exe dfshim.dll,ShArpMaintain MyApp.application, Culture=neutral, PublicKeyToken=31d7c5feac915835, processorArchitecture=msil

I'm working on a company-wide migration this week, and I would sincerely appreciate any help you can provide in resolving the uninstall error. Thanks!

**Comment by PaaaulZ** [comment]
Sorry for the delay. I updated the code and added a new release, please check with the new version.
Publish your log and uninstallString again if you have any problem

Thank you
